"""
Paquete `domain`

Contiene el núcleo del dominio de negocio del sistema UAT:

- Models: Entidades y objetos de valor que representan el negocio
- Repositories: Interfaces para el acceso a datos (contratos)
- Exceptions: Excepciones específicas del dominio

Esta capa es independiente de detalles técnicos y frameworks externos.
Contiene las reglas de negocio y la lógica central del sistema.

Ejemplos de uso:
    from domain import Bug, Campaign, BugRepository, CampaignRepository
    from domain.exceptions import DomainError
"""

from .models import (
    Block,
    Bug,
    BugHistory,
    Campaign,
    CampaignRun,
    Case,
    CaseRun,
    Drone,
    Email,
    Environment,
    File,
    Operator,
    Reason,
    Requirement,
    Section,
    Step,
    StepRun,
    System,
    UasZone,
    UhubOrg,
    UhubUser,
    Uspace,
    block_cases,
    bug_requirements,
    campaign_blocks,
    case_drones,
    case_operators,
    case_sections,
    case_systems,
    case_uas_zones,
    case_uhub_users,
    requirement_sections,
    requirement_systems,
    step_requirements,
    zone_organization,
    zone_reasons,
)
from .repositories import (
    BaseRepository,
    BlockRepository,
    BugRepository,
    CampaignRepository,
    CampaignRunRepository,
    CaseRepository,
    CaseRunRepository,
    DroneRepository,
    EmailRepository,
    EnvironmentRepository,
    FileRepository,
    OperatorRepository,
    ReasonRepository,
    RequirementRepository,
    SectionRepository,
    StepRepository,
    StepRunRepository,
    SystemRepository,
    UasZoneRepository,
    UhubOrgRepository,
    UhubUserRepository,
    UspaceRepository,
)

__all__ = [
    # Models
    "Email",
    "Operator",
    "Drone",
    "UhubOrg",
    "UhubUser",
    "UasZone",
    "Uspace",
    "Requirement",
    "Step",
    "Case",
    "Block",
    "Campaign",
    "CampaignRun",
    "CaseRun",
    "StepRun",
    "Bug",
    "BugHistory",
    "File",
    "Environment",
    "System",
    "Section",
    "Reason",
    "zone_organization",
    "zone_reasons",
    "requirement_systems",
    "requirement_sections",
    "step_requirements",
    "case_systems",
    "case_sections",
    "case_operators",
    "case_drones",
    "case_uhub_users",
    "case_uas_zones",
    "block_cases",
    "campaign_blocks",
    "bug_requirements",
    # Repositories
    "BaseRepository",
    "DroneRepository",
    "EmailRepository",
    "OperatorRepository",
    "UasZoneRepository",
    "UhubOrgRepository",
    "UhubUserRepository",
    "UspaceRepository",
    "BugRepository",
    "BlockRepository",
    "CampaignRepository",
    "CaseRepository",
    "StepRepository",
    "CampaignRunRepository",
    "CaseRunRepository",
    "StepRunRepository",
    "RequirementRepository",
    "EnvironmentRepository",
    "FileRepository",
    "ReasonRepository",
    "SectionRepository",
    "SystemRepository",
]
